name: urv-toolchain-test

on:
  workflow_run:
    workflows: [Container]
    types:
      - completed

jobs:

  urv-toolchain-test_wrc_and_urv_hello_sw:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: 'Run test'
        run: |
          podman pull ghcr.io/unike267/containers/urv-toolchain
          podman run --rm -tv $(pwd):/wrk:Z -w /wrk unike267/containers/urv-toolchain:latest ./test/urv-toolchain/test.sh
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: urv-toolchain-test
          path: |
            ./wrc.vhd
            ./wrc.bin
            ./wrc.bram
            ./hello.ram   
