name: Container

on:
  push:

env:
  REGISTRY_USER: unike267
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/unike267

permissions: write-all

jobs:

  impl_container:
    runs-on: ubuntu-latest
    
    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: '⛴️ Build container'
        run: podman build -t ghcr.io/unike267/containers/impl-arty - < .github/impl.containerfile

      - name: '🔑 Login to ghcr.io'
        run: echo $REGISTRY_PASSWORD | podman login $IMAGE_REGISTRY -u $REGISTRY_USER --password-stdin
      
      - name: '🛰️ Push image to ghcr.io'
        run: podman push ghcr.io/unike267/containers/impl-arty

      - name: '🔐 Logout of ghcr.io'
        run: podman logout $IMAGE_REGISTRY

  latex_container:
    runs-on: ubuntu-latest
    
    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: '⛴️ Build container'
        run: podman build -t ghcr.io/unike267/containers/latex-pygments - < .github/tex.containerfile

      - name: '🔑 Login to ghcr.io'
        run: echo $REGISTRY_PASSWORD | podman login $IMAGE_REGISTRY -u $REGISTRY_USER --password-stdin
      
      - name: '🛰️ Push image to ghcr.io'
        run: podman push ghcr.io/unike267/containers/latex-pygments

      - name: '🔐 Logout of ghcr.io'
        run: podman logout $IMAGE_REGISTRY

  urv-toolchain:
    runs-on: ubuntu-latest
    
    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: '⛴️ Build container'
        run: podman build -t ghcr.io/unike267/containers/urv-toolchain --target build - < .github/urv-toolchain.containerfile

      - name: '🔑 Login to ghcr.io'
        run: echo $REGISTRY_PASSWORD | podman login $IMAGE_REGISTRY -u $REGISTRY_USER --password-stdin
      
      - name: '🛰️ Push image to ghcr.io'
        run: podman push ghcr.io/unike267/containers/urv-toolchain

      - name: '🔐 Logout of ghcr.io'
        run: podman logout $IMAGE_REGISTRY
