name: Container

on:
  push:

env:
  REGISTRY_USER: unike267
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/unike267

permissions: write-all

jobs:

  latex_container:
    runs-on: ubuntu-latest
    
    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: '⛴️ Build container'
        run: podman build -t ghcr.io/unike267/containers/latex-pygments - < .github/tex.containerfile

      - name: '🔑 Login to ghcr.io'
        run: echo $REGISTRY_PASSWORD | podman login $IMAGE_REGISTRY -u $REGISTRY_USER --password-stdin
      
      - name: '🛰️ Push image to ghcr.io'
        run: podman push ghcr.io/unike267/containers/latex-pygments

      - name: '🔐 Logout of ghcr.io'
        run: podman logout $IMAGE_REGISTRY

  latex_test:
    runs-on: ubuntu-latest
    needs: latex_container

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/unike267/containers/latex-pygments:latest
        with:
          args: ./test/latex-test/make.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: pdf_output
          path: ./test/latex-test/latex-test.pdf
