name: lm32-Toolchain-Container

on:
  push:

env:
  REGISTRY_USER: unike267
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/unike267

permissions: write-all

jobs:

  lm32-toolchain:
    runs-on: ubuntu-latest
    
    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: '⛴️ Build container'
        run: podman build -t ghcr.io/unike267/containers/lm32-toolchain --target build - < .github/lm32-toolchain.containerfile

      - name: '🔑 Login to ghcr.io'
        run: echo $REGISTRY_PASSWORD | podman login $IMAGE_REGISTRY -u $REGISTRY_USER --password-stdin
      
      - name: '🛰️ Push image to ghcr.io'
        run: podman push ghcr.io/unike267/containers/lm32-toolchain

      - name: '🔐 Logout of ghcr.io'
        run: podman logout $IMAGE_REGISTRY

  lm32-toolchain-test:
    runs-on: ubuntu-latest
    needs: lm32-toolchain

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: 'Run test'
        run: |
          cd test/lm32-toolchain
          git clone --recursive https://ohwr.org/project/wrpc-sw
          cd wrpc-sw/
          git checkout origin/hm-cute-a7-v4.2
          git switch hm-cute-a7-v4.2
          cd ppsi/
          git checkout origin/hm-cute-a7-v4.2
          cd ..
          podman pull ghcr.io/unike267/containers/lm32-toolchain
          podman run --rm -tv $(pwd):/wrk:Z -w /wrk unike267/containers/lm32-toolchain:latest ./test.sh
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: lm32-toolchain-test
          path: |
            ./wrc.vhd
            ./wrc.bin
            ./wrc.elf
            ./wrc.bram
